SET FOREIGN_KEY_CHECKS=0

DROP TABLE IF EXISTS `ADMINISTRADOR` CASCADE
;

DROP TABLE IF EXISTS `AULA` CASCADE
;

DROP TABLE IF EXISTS `AULA_ASOCIA_FECHA` CASCADE
;

DROP TABLE IF EXISTS `BEDEL` CASCADE
;

DROP TABLE IF EXISTS `CATEDRA` CASCADE
;

DROP TABLE IF EXISTS `DIA` CASCADE
;

DROP TABLE IF EXISTS `DIA_PERTENECE_A_PERIODICA` CASCADE
;

DROP TABLE IF EXISTS `DOCENTE` CASCADE
;

DROP TABLE IF EXISTS `DOCENTE_PERTENECE_CATEDRA` CASCADE
;

DROP TABLE IF EXISTS `ESPORADICA` CASCADE
;

DROP TABLE IF EXISTS `FECHA` CASCADE
;

DROP TABLE IF EXISTS `HISTORIAL_CONTRASENIAS` CASCADE
;

DROP TABLE IF EXISTS `INFORMATICA` CASCADE
;

DROP TABLE IF EXISTS `MULTIMEDIOS` CASCADE
;

DROP TABLE IF EXISTS `PERIODICA` CASCADE
;

DROP TABLE IF EXISTS `PERIODO` CASCADE
;

DROP TABLE IF EXISTS `POLITICA_CONTRASENIAS` CASCADE
;

DROP TABLE IF EXISTS `RESERVA` CASCADE
;

DROP TABLE IF EXISTS `SIN_RECURSOS` CASCADE
;

DROP TABLE IF EXISTS `TURNO` CASCADE
;

DROP TABLE IF EXISTS `USUARIO` CASCADE
;

CREATE TABLE `ADMINISTRADOR`
(
	`id_admin` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`id_usuario` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	CONSTRAINT `PK_ADMINISTRADOR` PRIMARY KEY (`id_admin`)
)
;

CREATE TABLE `AULA`
(
	`id_aula` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`ubicacion` INT,
	`capacidad` INT,
	`estado` VARCHAR(13),
	`tipo_pizarron` VARCHAR(8),
	`aire_acondicionado` VARCHAR(2),
	`id_reserva` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	CONSTRAINT `PK_AULA` PRIMARY KEY (`id_aula`)
)
;

CREATE TABLE `AULA_ASOCIA_FECHA`
(
	`id_fecha` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`id_aula` INT AUTO_INCREMENT UNIQUE ,
	CONSTRAINT `PK_ASOCIA` PRIMARY KEY (`id_fecha`)
)
;

CREATE TABLE `BEDEL`
(
	`id_bedel` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`nombre_bedel` VARCHAR(20),
	`apellido_bedel` VARCHAR(20),
	`id_usuario` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`id_turno` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	CONSTRAINT `PK_BEDEL` PRIMARY KEY (`id_bedel`)
)
;

CREATE TABLE `CATEDRA`
(
	`id_catedra` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`nombre_catedra` VARCHAR(20),
	CONSTRAINT `PK_CATEDRA` PRIMARY KEY (`id_catedra`)
)
;

CREATE TABLE `DIA`
(
	`id_dia` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`nombre_dia` VARCHAR(9),
	CONSTRAINT `PK_DIA` PRIMARY KEY (`id_dia`)
)
;

CREATE TABLE `DIA_PERTENECE_A_PERIODICA`
(
	`id_dia` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	CONSTRAINT `PK_PERTENECE_A` PRIMARY KEY (`id_dia`)
)
;

CREATE TABLE `DOCENTE`
(
	`id_docente` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`nombre_docente` VARCHAR(20),
	`apellido_docente` VARCHAR(20),
	`email_docente` VARCHAR(30),
	CONSTRAINT `PK_DOCENTE` PRIMARY KEY (`id_docente`)
)
;

CREATE TABLE `DOCENTE_PERTENECE_CATEDRA`
(
	`id_catedra` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`id_docente` INT NOT NULL AUTO_INCREMENT UNIQUE 
)
;

CREATE TABLE `ESPORADICA`
(
	`id_reserva` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	CONSTRAINT `PK_ESPORADICA` PRIMARY KEY (`id_reserva`)
)
;

CREATE TABLE `FECHA`
(
	`id_fecha` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`duracion` INT,
	`hora_inicio` TIME(0),
	`fecha` DATE,
	`id_dia` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`id_reserva` INT,
	CONSTRAINT `PK_FECHA` PRIMARY KEY (`id_fecha`)
)
;

CREATE TABLE `HISTORIAL_CONTRASENIAS`
(
	`id_cambio` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`fecha_cambio` DATE,
	`contrasenia_nueva` VARCHAR(20),
	`id_usuario` INT ZEROFILL NOT NULL AUTO_INCREMENT UNIQUE ,
	`id_politica` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	CONSTRAINT `PK_HISTORIAL_CONTRASENIAS` PRIMARY KEY (`id_cambio`)
)
;

CREATE TABLE `INFORMATICA`
(
	`canion` VARCHAR(2),
	`cantidad_pcs` INT,
	`id_aula` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	CONSTRAINT `PK_INFORMATICA` PRIMARY KEY (`id_aula`)
)
;

CREATE TABLE `MULTIMEDIOS`
(
	`televisor` VARCHAR(2),
	`canion` VARCHAR(2),
	`computadora` VARCHAR(2),
	`dvd` VARCHAR(2),
	`id_aula` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	CONSTRAINT `PK_MULTIMEDIOS` PRIMARY KEY (`id_aula`)
)
;

CREATE TABLE `PERIODICA`
(
	`id_reserva` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`id_periodo` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	CONSTRAINT `PK_PERIODICA` PRIMARY KEY (`id_reserva`)
)
;

CREATE TABLE `PERIODO`
(
	`id_periodo` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`tipo_periodo` VARCHAR(13),
	`fecha_inicio` DATE,
	`fecha_fin` DATE,
	CONSTRAINT `PK_PERIODO` PRIMARY KEY (`id_periodo`)
)
;

CREATE TABLE `POLITICA_CONTRASENIAS`
(
	`id_politica` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`tipo_politica` TEXT,
	CONSTRAINT `PK_POLITICA_CONTRASENIAS` PRIMARY KEY (`id_politica`)
)
;

CREATE TABLE `RESERVA`
(
	`id_reserva` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`cantidad_alumnos` INT,
	`id_bedel` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`id_catedra` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`id_docente` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	CONSTRAINT `PK_RESERVA` PRIMARY KEY (`id_reserva`)
)
;

CREATE TABLE `SIN_RECURSOS`
(
	`ventiladores` VARCHAR(2),
	`id_aula` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	CONSTRAINT `PK_SIN_RECURSOS` PRIMARY KEY (`id_aula`)
)
;

CREATE TABLE `TURNO`
(
	`id_turno` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`nombre_turno` VARCHAR(6) NOT NULL,
	CONSTRAINT `PK_TURNO` PRIMARY KEY (`id_turno`)
)
;

CREATE TABLE `USUARIO`
(
	`id_usuario` INT NOT NULL AUTO_INCREMENT UNIQUE ,
	`nombre_usuario` VARCHAR(20) NOT NULL,
	`contrasenia` VARCHAR(20) NOT NULL,
	CONSTRAINT `PK_USUARIO` PRIMARY KEY (`id_usuario`)
)
;

ALTER TABLE `ADMINISTRADOR` 
 ADD CONSTRAINT `FK_ADMINISTRADOR_USUARIO`
	FOREIGN KEY (`id_usuario`) REFERENCES `USUARIO` (`id_usuario`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `AULA` 
 ADD CONSTRAINT `FK_ASIGNA_RESERVA`
	FOREIGN KEY (`id_reserva`) REFERENCES `RESERVA` (`id_reserva`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `AULA_ASOCIA_FECHA` 
 ADD CONSTRAINT `FK_ASOCIA_FECHA`
	FOREIGN KEY (`id_fecha`) REFERENCES `FECHA` (`id_fecha`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `AULA_ASOCIA_FECHA` 
 ADD CONSTRAINT `FK_ASOCIA_AULA`
	FOREIGN KEY (`id_aula`) REFERENCES `AULA` (`id_aula`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `BEDEL` 
 ADD CONSTRAINT `FK_BEDEL_USUARIO`
	FOREIGN KEY (`id_usuario`) REFERENCES `USUARIO` (`id_usuario`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `BEDEL` 
 ADD CONSTRAINT `FK_PERTENECE_A_TURNO`
	FOREIGN KEY (`id_turno`) REFERENCES `TURNO` (`id_turno`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `DIA_PERTENECE_A_PERIODICA` 
 ADD CONSTRAINT `FK_PERTENECE_A_DIA`
	FOREIGN KEY (`id_dia`) REFERENCES `DIA` (`id_dia`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `DOCENTE_PERTENECE_CATEDRA` 
 ADD CONSTRAINT `FK_PERTENECE_CATEDRA`
	FOREIGN KEY (`id_catedra`) REFERENCES `CATEDRA` (`id_catedra`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `DOCENTE_PERTENECE_CATEDRA` 
 ADD CONSTRAINT `FK_PERTENECE_DOCENTE`
	FOREIGN KEY (`id_docente`) REFERENCES `DOCENTE` (`id_docente`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `ESPORADICA` 
 ADD CONSTRAINT `FK_ESPORADICA_RESERVA`
	FOREIGN KEY (`id_reserva`) REFERENCES `RESERVA` (`id_reserva`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `FECHA` 
 ADD CONSTRAINT `FK_INCLUYE_DIA`
	FOREIGN KEY (`id_dia`) REFERENCES `DIA` (`id_dia`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `HISTORIAL_CONTRASENIAS` 
 ADD CONSTRAINT `FK_REGISTRA_HISTORIAL_CONTRASENIAS`
	FOREIGN KEY (`id_usuario`) REFERENCES `USUARIO` (`id_usuario`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `HISTORIAL_CONTRASENIAS` 
 ADD CONSTRAINT `FK_RESPETA_HISTORIAL_CONTRASENIAS`
	FOREIGN KEY (`id_politica`) REFERENCES `POLITICA_CONTRASENIAS` (`id_politica`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `INFORMATICA` 
 ADD CONSTRAINT `FK_INFORMATICA_AULA`
	FOREIGN KEY (`id_aula`) REFERENCES `AULA` (`id_aula`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MULTIMEDIOS` 
 ADD CONSTRAINT `FK_MULTIMEDIOS_AULA`
	FOREIGN KEY (`id_aula`) REFERENCES `AULA` (`id_aula`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `PERIODICA` 
 ADD CONSTRAINT `FK_PERIODICA_RESERVA`
	FOREIGN KEY (`id_reserva`) REFERENCES `RESERVA` (`id_reserva`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `PERIODICA` 
 ADD CONSTRAINT `FK_ABARCA_PERIODO`
	FOREIGN KEY (`id_periodo`) REFERENCES `PERIODO` (`id_periodo`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `RESERVA` 
 ADD CONSTRAINT `FK_REGISTRA_BEDEL`
	FOREIGN KEY (`id_bedel`) REFERENCES `BEDEL` (`id_bedel`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `RESERVA` 
 ADD CONSTRAINT `FK_ASOCIA_CATEDRA`
	FOREIGN KEY (`id_catedra`) REFERENCES `CATEDRA` (`id_catedra`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `RESERVA` 
 ADD CONSTRAINT `FK_SOLICITA_RESERVA`
	FOREIGN KEY (`id_docente`) REFERENCES `DOCENTE` (`id_docente`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `SIN_RECURSOS` 
 ADD CONSTRAINT `FK_SIN_RECURSOS_AULA`
	FOREIGN KEY (`id_aula`) REFERENCES `AULA` (`id_aula`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1
