SET FOREIGN_KEY_CHECKS=0;



DROP TABLE IF EXISTS ADMINISTRADOR;
DROP TABLE IF EXISTS AULA;
DROP TABLE IF EXISTS AULA_ASOCIA_FECHA;
DROP TABLE IF EXISTS BEDEL;
DROP TABLE IF EXISTS CATEDRA;
DROP TABLE IF EXISTS DIA;
DROP TABLE IF EXISTS DIA_PERTENECE_A_PERIODICA;
DROP TABLE IF EXISTS DOCENTE;
DROP TABLE IF EXISTS DOCENTE_PERTENECE_CATEDRA;
DROP TABLE IF EXISTS ESPORADICA;
DROP TABLE IF EXISTS FECHA;
DROP TABLE IF EXISTS HISTORIAL_CONTRASENIAS;
DROP TABLE IF EXISTS INFORMATICA;
DROP TABLE IF EXISTS MULTIMEDIOS;
DROP TABLE IF EXISTS PERIODICA;
DROP TABLE IF EXISTS PERIODO;
DROP TABLE IF EXISTS POLITICA_CONTRASENIAS;
DROP TABLE IF EXISTS RESERVA;
DROP TABLE IF EXISTS SIN_RECURSOS;
DROP TABLE IF EXISTS TURNO;
DROP TABLE IF EXISTS USUARIO;

CREATE TABLE ADMINISTRADOR
(
	id_admin INT NOT NULL,
	id_usuario INT NOT NULL,
	PRIMARY KEY (id_admin),
	KEY (id_usuario)
) ;


CREATE TABLE AULA
(
	id_aula INT NOT NULL,
	ubicacion INT,
	capacidad INT,
	estado VARCHAR(13),
	tipo_pizarron VARCHAR(8),
	aire_acondicionado VARCHAR(2),
	id_reserva INT NOT NULL,
	PRIMARY KEY (id_aula),
	KEY (id_reserva)
) ;


CREATE TABLE AULA_ASOCIA_FECHA
(
	id_fecha INT NOT NULL,
	id_aula INT,
	PRIMARY KEY (id_fecha),
	KEY (id_fecha),
	KEY (id_aula)
) ;


CREATE TABLE BEDEL
(
	id_bedel INT NOT NULL,
	nombre_bedel VARCHAR(20),
	apellido_bedel VARCHAR(20),
	id_usuario INT NOT NULL,
	id_turno INT NOT NULL,
	PRIMARY KEY (id_bedel),
	KEY (id_usuario),
	KEY (id_turno)
) ;


CREATE TABLE CATEDRA
(
	id_catedra INT NOT NULL,
	nombre_catedra VARCHAR(20),
	PRIMARY KEY (id_catedra)
) ;


CREATE TABLE DIA
(
	id_dia INT NOT NULL,
	nombre_dia VARCHAR(9),
	PRIMARY KEY (id_dia)
) ;


CREATE TABLE DIA_PERTENECE_A_PERIODICA
(
	id_dia INT NOT NULL,
	PRIMARY KEY (id_dia),
	KEY (id_dia)
) ;


CREATE TABLE DOCENTE
(
	id_docente INT NOT NULL,
	nombre_docente VARCHAR(20),
	apellido_docente VARCHAR(20),
	email_docente VARCHAR(30),
	PRIMARY KEY (id_docente)
) ;


CREATE TABLE DOCENTE_PERTENECE_CATEDRA
(
	id_catedra INT NOT NULL,
	id_docente INT NOT NULL,
	KEY (id_catedra),
	KEY (id_docente)
) ;


CREATE TABLE ESPORADICA
(
	id_reserva INT NOT NULL,
	PRIMARY KEY (id_reserva),
	KEY (id_reserva)
) ;


CREATE TABLE FECHA
(
	id_fecha INT NOT NULL,
	duracion INT,
	hora_inicio TIME(0),
	fecha DATE,
	id_dia INT NOT NULL,
	id_reserva INT,
	PRIMARY KEY (id_fecha),
	KEY (id_dia)
) ;


CREATE TABLE HISTORIAL_CONTRASENIAS
(
	id_cambio INT NOT NULL,
	fecha_cambio DATE,
	contrasenia_nueva VARCHAR(20),
	id_usuario INT NOT NULL,
	id_politica INT NOT NULL,
	PRIMARY KEY (id_cambio),
	KEY (id_usuario),
	KEY (id_politica)
) ;


CREATE TABLE INFORMATICA
(
	canion VARCHAR(2),
	cantidad_pcs INT,
	id_aula INT NOT NULL,
	PRIMARY KEY (id_aula),
	KEY (id_aula)
) ;


CREATE TABLE MULTIMEDIOS
(
	televisor VARCHAR(2),
	canion VARCHAR(2),
	computadora VARCHAR(2),
	dvd VARCHAR(2),
	id_aula INT NOT NULL,
	PRIMARY KEY (id_aula),
	KEY (id_aula)
) ;


CREATE TABLE PERIODICA
(
	id_reserva INT NOT NULL,
	id_periodo INT NOT NULL,
	PRIMARY KEY (id_reserva),
	KEY (id_reserva),
	KEY (id_periodo)
) ;


CREATE TABLE PERIODO
(
	id_periodo INT NOT NULL,
	tipo_periodo VARCHAR(13),
	fecha_inicio DATE,
	fecha_fin DATE,
	PRIMARY KEY (id_periodo)
) ;


CREATE TABLE POLITICA_CONTRASENIAS
(
	id_politica INT NOT NULL,
	tipo_politica TEXT,
	PRIMARY KEY (id_politica)
) ;


CREATE TABLE RESERVA
(
	id_reserva INT NOT NULL,
	cantidad_alumnos INT,
	id_bedel INT NOT NULL,
	id_catedra INT NOT NULL,
	id_docente INT NOT NULL,
	PRIMARY KEY (id_reserva),
	KEY (id_bedel),
	KEY (id_catedra),
	KEY (id_docente)
) ;


CREATE TABLE SIN_RECURSOS
(
	ventiladores VARCHAR(2),
	id_aula INT NOT NULL,
	PRIMARY KEY (id_aula),
	KEY (id_aula)
) ;


CREATE TABLE TURNO
(
	id_turno INT NOT NULL,
	nombre_turno VARCHAR(6) NOT NULL,
	PRIMARY KEY (id_turno)
) ;


CREATE TABLE USUARIO
(
	id_usuario INT NOT NULL,
	nombre_usuario VARCHAR(20) NOT NULL,
	contrasenia VARCHAR(20) NOT NULL,
	PRIMARY KEY (id_usuario)
) ;



SET FOREIGN_KEY_CHECKS=1;


ALTER TABLE ADMINISTRADOR ADD CONSTRAINT FK_ADMINISTRADOR_USUARIO 
	FOREIGN KEY (id_usuario) REFERENCES USUARIO (id_usuario);

ALTER TABLE AULA ADD CONSTRAINT FK_ASIGNA_RESERVA 
	FOREIGN KEY (id_reserva) REFERENCES RESERVA (id_reserva);

ALTER TABLE AULA_ASOCIA_FECHA ADD CONSTRAINT FK_ASOCIA_FECHA 
	FOREIGN KEY (id_fecha) REFERENCES FECHA (id_fecha);

ALTER TABLE AULA_ASOCIA_FECHA ADD CONSTRAINT FK_ASOCIA_AULA 
	FOREIGN KEY (id_aula) REFERENCES AULA (id_aula);

ALTER TABLE BEDEL ADD CONSTRAINT FK_BEDEL_USUARIO 
	FOREIGN KEY (id_usuario) REFERENCES USUARIO (id_usuario);

ALTER TABLE BEDEL ADD CONSTRAINT FK_PERTENECE_A_TURNO 
	FOREIGN KEY (id_turno) REFERENCES TURNO (id_turno);

ALTER TABLE DIA_PERTENECE_A_PERIODICA ADD CONSTRAINT FK_PERTENECE_A_DIA 
	FOREIGN KEY (id_dia) REFERENCES DIA (id_dia);

ALTER TABLE DOCENTE_PERTENECE_CATEDRA ADD CONSTRAINT FK_PERTENECE_CATEDRA 
	FOREIGN KEY (id_catedra) REFERENCES CATEDRA (id_catedra);

ALTER TABLE DOCENTE_PERTENECE_CATEDRA ADD CONSTRAINT FK_PERTENECE_DOCENTE 
	FOREIGN KEY (id_docente) REFERENCES DOCENTE (id_docente);

ALTER TABLE ESPORADICA ADD CONSTRAINT FK_ESPORADICA_RESERVA 
	FOREIGN KEY (id_reserva) REFERENCES RESERVA (id_reserva);

ALTER TABLE FECHA ADD CONSTRAINT FK_INCLUYE_DIA 
	FOREIGN KEY (id_dia) REFERENCES DIA (id_dia);

ALTER TABLE HISTORIAL_CONTRASENIAS ADD CONSTRAINT FK_REGISTRA_HISTORIAL_CONTRASENIAS 
	FOREIGN KEY (id_usuario) REFERENCES USUARIO (id_usuario);

ALTER TABLE HISTORIAL_CONTRASENIAS ADD CONSTRAINT FK_RESPETA_HISTORIAL_CONTRASENIAS 
	FOREIGN KEY (id_politica) REFERENCES POLITICA_CONTRASENIAS (id_politica);

ALTER TABLE INFORMATICA ADD CONSTRAINT FK_INFORMATICA_AULA 
	FOREIGN KEY (id_aula) REFERENCES AULA (id_aula);

ALTER TABLE MULTIMEDIOS ADD CONSTRAINT FK_MULTIMEDIOS_AULA 
	FOREIGN KEY (id_aula) REFERENCES AULA (id_aula);

ALTER TABLE PERIODICA ADD CONSTRAINT FK_PERIODICA_RESERVA 
	FOREIGN KEY (id_reserva) REFERENCES RESERVA (id_reserva);

ALTER TABLE PERIODICA ADD CONSTRAINT FK_ABARCA_PERIODO 
	FOREIGN KEY (id_periodo) REFERENCES PERIODO (id_periodo);

ALTER TABLE RESERVA ADD CONSTRAINT FK_REGISTRA_BEDEL 
	FOREIGN KEY (id_bedel) REFERENCES BEDEL (id_bedel);

ALTER TABLE RESERVA ADD CONSTRAINT FK_ASOCIA_CATEDRA 
	FOREIGN KEY (id_catedra) REFERENCES CATEDRA (id_catedra);

ALTER TABLE RESERVA ADD CONSTRAINT FK_SOLICITA_RESERVA 
	FOREIGN KEY (id_docente) REFERENCES DOCENTE (id_docente);

ALTER TABLE SIN_RECURSOS ADD CONSTRAINT FK_SIN_RECURSOS_AULA 
	FOREIGN KEY (id_aula) REFERENCES AULA (id_aula);
