package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1



/**
 * Administrador generated by hbm2java
 */
public class Administrador extends Usuario implements java.io.Serializable {

    public Administrador() {
    }

    public Administrador(String usuario) {
       super.setNombreUsuario(usuario);
    }

}


