package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Aula generated by hbm2java
 */
public class Aula  implements java.io.Serializable {


     private Integer idAula;
     private Integer ubicacion;
     private Integer capacidad;
     private String estado;
     private String tipoPizarron;
     private String aireAcondicionado;
     private Set aulaAsociaFechas = new HashSet(0);


    public Aula() {
    }

	

    public Aula(Integer ubicacion, Integer capacidad, String estado, String tipoPizarron, String aireAcondicionado, Set aulaAsociaFechas) {

       this.ubicacion = ubicacion;
       this.capacidad = capacidad;
       this.estado = estado;
       this.tipoPizarron = tipoPizarron;
       this.aireAcondicionado = aireAcondicionado;
       this.aulaAsociaFechas = aulaAsociaFechas;
    }
   
    public Integer getIdAula() {
        return this.idAula;
    }
    
    public void setIdAula(Integer idAula) {
        this.idAula = idAula;
    }
    public Integer getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(Integer ubicacion) {
        this.ubicacion = ubicacion;
    }
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getTipoPizarron() {
        return this.tipoPizarron;
    }
    
    public void setTipoPizarron(String tipoPizarron) {
        this.tipoPizarron = tipoPizarron;
    }
    public String getAireAcondicionado() {
        return this.aireAcondicionado;
    }
    
    public void setAireAcondicionado(String aireAcondicionado) {
        this.aireAcondicionado = aireAcondicionado;
    }
    public Set getAulaAsociaFechas() {
        return this.aulaAsociaFechas;
    }
    
    public void setAulaAsociaFechas(Set aulaAsociaFechas) {
        this.aulaAsociaFechas = aulaAsociaFechas;
    }
   
}


