package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bedel generated by hbm2java
 */
public class Bedel  implements java.io.Serializable {


     private Integer idBedel;
     private Turno turno;
     private Usuario usuario;
     private String nombreBedel;
     private String apellidoBedel;
     private Set reservas = new HashSet(0);

    public Bedel() {
    }

	
    public Bedel(Turno turno, Usuario usuario) {
        this.turno = turno;
        this.usuario = usuario;
    }
    public Bedel(Turno turno, Usuario usuario, String nombreBedel, String apellidoBedel, Set reservas) {
       this.turno = turno;
       this.usuario = usuario;
       this.nombreBedel = nombreBedel;
       this.apellidoBedel = apellidoBedel;
       this.reservas = reservas;
    }
   
    public Integer getIdBedel() {
        return this.idBedel;
    }
    
    public void setIdBedel(Integer idBedel) {
        this.idBedel = idBedel;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombreBedel() {
        return this.nombreBedel;
    }
    
    public void setNombreBedel(String nombreBedel) {
        this.nombreBedel = nombreBedel;
    }
    public String getApellidoBedel() {
        return this.apellidoBedel;
    }
    
    public void setApellidoBedel(String apellidoBedel) {
        this.apellidoBedel = apellidoBedel;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


