package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bedel generated by hbm2java
 */
public class Bedel extends Usuario implements java.io.Serializable {

     private Integer idBedel;
     private Turno turno;
     private String nombreBedel;
     private String apellidoBedel;

    public Bedel() {
    }

	
    public Bedel(Turno turno, String usuario) {
        this.turno = turno;
        super.setNombreUsuario(usuario);
    }
    public Bedel(Turno turno, String usuario, String contraseña, String nombreBedel, String apellidoBedel) {
       this.turno = turno;
       super.setNombreUsuario(usuario);
       super.setContrasenia(contraseña);
       this.nombreBedel = nombreBedel;
       this.apellidoBedel = apellidoBedel;
    }
   
    public Integer getIdBedel() {
        return this.idBedel;
    }
    
    public void setIdBedel(Integer idBedel) {
        this.idBedel = idBedel;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public String getNombreBedel() {
        return this.nombreBedel;
    }
    
    public void setNombreBedel(String nombreBedel) {
        this.nombreBedel = nombreBedel;
    }
    public String getApellidoBedel() {
        return this.apellidoBedel;
    }
    
    public void setApellidoBedel(String apellidoBedel) {
        this.apellidoBedel = apellidoBedel;
    }

}


