package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Catedra generated by hbm2java
 */
public class Catedra  implements java.io.Serializable {


     private Integer idCatedra;
     private String nombreCatedra;
     private Set docentePerteneceCatedras = new HashSet(0);
     private Set reservas = new HashSet(0);

    public Catedra() {
    }

    public Catedra(String nombreCatedra, Set docentePerteneceCatedras, Set reservas) {
       this.nombreCatedra = nombreCatedra;
       this.docentePerteneceCatedras = docentePerteneceCatedras;
       this.reservas = reservas;
    }
   
    public Integer getIdCatedra() {
        return this.idCatedra;
    }
    
    public void setIdCatedra(Integer idCatedra) {
        this.idCatedra = idCatedra;
    }
    public String getNombreCatedra() {
        return this.nombreCatedra;
    }
    
    public void setNombreCatedra(String nombreCatedra) {
        this.nombreCatedra = nombreCatedra;
    }
    public Set getDocentePerteneceCatedras() {
        return this.docentePerteneceCatedras;
    }
    
    public void setDocentePerteneceCatedras(Set docentePerteneceCatedras) {
        this.docentePerteneceCatedras = docentePerteneceCatedras;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }




}


