package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dia generated by hbm2java
 */
public class Dia  implements java.io.Serializable {


     private Integer idDia;
     private String nombreDia;
     private Set fechas = new HashSet(0);
     private DiaPerteneceAPeriodica diaPerteneceAPeriodica;

    public Dia() {
    }

    public Dia(String nombreDia, Set fechas, DiaPerteneceAPeriodica diaPerteneceAPeriodica) {
       this.nombreDia = nombreDia;
       this.fechas = fechas;
       this.diaPerteneceAPeriodica = diaPerteneceAPeriodica;
    }
   
    public Integer getIdDia() {
        return this.idDia;
    }
    
    public void setIdDia(Integer idDia) {
        this.idDia = idDia;
    }
    public String getNombreDia() {
        return this.nombreDia;
    }
    
    public void setNombreDia(String nombreDia) {
        this.nombreDia = nombreDia;
    }
    public Set getFechas() {
        return this.fechas;
    }
    
    public void setFechas(Set fechas) {
        this.fechas = fechas;
    }
    public DiaPerteneceAPeriodica getDiaPerteneceAPeriodica() {
        return this.diaPerteneceAPeriodica;
    }
    
    public void setDiaPerteneceAPeriodica(DiaPerteneceAPeriodica diaPerteneceAPeriodica) {
        this.diaPerteneceAPeriodica = diaPerteneceAPeriodica;
    }




}


