package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1



/**
 * DiaPerteneceAPeriodica generated by hbm2java
 */
public class DiaPerteneceAPeriodica  implements java.io.Serializable {


     private int idDia;
     private Dia dia;

    public DiaPerteneceAPeriodica() {
    }

    public DiaPerteneceAPeriodica(Dia dia) {
       this.dia = dia;
    }
   
    public int getIdDia() {
        return this.idDia;
    }
    
    public void setIdDia(int idDia) {
        this.idDia = idDia;
    }
    public Dia getDia() {
        return this.dia;
    }
    
    public void setDia(Dia dia) {
        this.dia = dia;
    }




}


