package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1



/**
 * DocentePerteneceCatedraId generated by hbm2java
 */
public class DocentePerteneceCatedraId  implements java.io.Serializable {


     private int idCatedra;
     private int idDocente;

    public DocentePerteneceCatedraId() {
    }

    public DocentePerteneceCatedraId(int idCatedra, int idDocente) {
       this.idCatedra = idCatedra;
       this.idDocente = idDocente;
    }
   
    public int getIdCatedra() {
        return this.idCatedra;
    }
    
    public void setIdCatedra(int idCatedra) {
        this.idCatedra = idCatedra;
    }
    public int getIdDocente() {
        return this.idDocente;
    }
    
    public void setIdDocente(int idDocente) {
        this.idDocente = idDocente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DocentePerteneceCatedraId) ) return false;
		 DocentePerteneceCatedraId castOther = ( DocentePerteneceCatedraId ) other; 
         
		 return (this.getIdCatedra()==castOther.getIdCatedra())
 && (this.getIdDocente()==castOther.getIdDocente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCatedra();
         result = 37 * result + this.getIdDocente();
         return result;
   }   


}


