package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1



/**
 * DocentePerteneceCatedra generated by hbm2java
 */
public class DocentePerteneceCatedra  implements java.io.Serializable {


     private DocentePerteneceCatedraId id;
     private Catedra catedra;
     private Docente docente;

    public DocentePerteneceCatedra() {
    }

    public DocentePerteneceCatedra(DocentePerteneceCatedraId id, Catedra catedra, Docente docente) {
       this.id = id;
       this.catedra = catedra;
       this.docente = docente;
    }
   
    public DocentePerteneceCatedraId getId() {
        return this.id;
    }
    
    public void setId(DocentePerteneceCatedraId id) {
        this.id = id;
    }
    public Catedra getCatedra() {
        return this.catedra;
    }
    
    public void setCatedra(Catedra catedra) {
        this.catedra = catedra;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }




}


