package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1



/**
 * Esporadica generated by hbm2java
 */
public class Esporadica extends Reserva implements java.io.Serializable {
    

}


