package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1



/**
 * Esporadica generated by hbm2java
 */
public class Esporadica  implements java.io.Serializable {


     private int idReserva;
     private Reserva reserva;

    public Esporadica() {
    }

    public Esporadica(Reserva reserva) {
       this.reserva = reserva;
    }
   
    public int getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(int idReserva) {
        this.idReserva = idReserva;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }




}


