package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Esporadica generated by hbm2java
 */
public class Esporadica extends Reserva implements java.io.Serializable {
    
    private Set fechas = new HashSet(0);

    public Set getFechas() {
        return fechas;
    }

    public void setFechas(Set fechas) {
        this.fechas = fechas;
    }
    

}


