package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Fecha generated by hbm2java
 */
public class Fecha  implements java.io.Serializable {


     private Integer idFecha;
     private Dia dia;
     private Integer duracion;
     private Date horaInicio;
     private Date fecha;
     private Esporadica esporadica;
     private Aula aula;

    public Fecha() {
    }

	
    public Fecha(Dia dia) {
        this.dia = dia;
    }

    public Fecha(Integer idFecha, Dia dia, Integer duracion, Date horaInicio, Date fecha, Aula aula) {
        this.idFecha = idFecha;
        this.dia = dia;
        this.duracion = duracion;
        this.horaInicio = horaInicio;
        this.fecha = fecha;
        this.aula = aula;
    }

    public Fecha(Integer idFecha, Dia dia, Integer duracion, Date horaInicio, Date fecha, Esporadica esporadica, Aula aula) {
        this.idFecha = idFecha;
        this.dia = dia;
        this.duracion = duracion;
        this.horaInicio = horaInicio;
        this.fecha = fecha;
        this.esporadica = esporadica;
        this.aula = aula;
    }
      
    public Integer getIdFecha() {
        return this.idFecha;
    }
    
    public void setIdFecha(Integer idFecha) {
        this.idFecha = idFecha;
    }
    public Dia getDia() {
        return this.dia;
    }
    
    public void setDia(Dia dia) {
        this.dia = dia;
    }
    public Integer getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Integer duracion) {
        this.duracion = duracion;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    public void setEsporadica(Esporadica esporadica) {
        this.esporadica = esporadica;
    }

    public void setAula(Aula aula) {
        this.aula = aula;
    }

    public Esporadica getEsporadica() {
        return esporadica;
    }

    public Aula getAula() {
        return aula;
    }

}


