package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Fecha generated by hbm2java
 */
public class Fecha  implements java.io.Serializable {


     private Integer idFecha;
     private Dia dia;
     private Integer duracion;
     private Date horaInicio;
     private Date fecha;
     private Integer idReserva;
     private AulaAsociaFecha aulaAsociaFecha;

    public Fecha() {
    }

	
    public Fecha(Dia dia) {
        this.dia = dia;
    }
    public Fecha(Dia dia, Integer duracion, Date horaInicio, Date fecha, Integer idReserva, AulaAsociaFecha aulaAsociaFecha) {
       this.dia = dia;
       this.duracion = duracion;
       this.horaInicio = horaInicio;
       this.fecha = fecha;
       this.idReserva = idReserva;
       this.aulaAsociaFecha = aulaAsociaFecha;
    }
   
    public Integer getIdFecha() {
        return this.idFecha;
    }
    
    public void setIdFecha(Integer idFecha) {
        this.idFecha = idFecha;
    }
    public Dia getDia() {
        return this.dia;
    }
    
    public void setDia(Dia dia) {
        this.dia = dia;
    }
    public Integer getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Integer duracion) {
        this.duracion = duracion;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(Integer idReserva) {
        this.idReserva = idReserva;
    }
    public AulaAsociaFecha getAulaAsociaFecha() {
        return this.aulaAsociaFecha;
    }
    
    public void setAulaAsociaFecha(AulaAsociaFecha aulaAsociaFecha) {
        this.aulaAsociaFecha = aulaAsociaFecha;
    }




}


