package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HistorialContrasenias generated by hbm2java
 */
public class HistorialContrasenias  implements java.io.Serializable {


     private Integer idCambio;
     private PoliticaContrasenias politicaContrasenias;
     private Usuario usuario;
     private Date fechaCambio;
     private String contraseniaNueva;

    public HistorialContrasenias() {
    }

	
    public HistorialContrasenias(PoliticaContrasenias politicaContrasenias, Usuario usuario) {
        this.politicaContrasenias = politicaContrasenias;
        this.usuario = usuario;
    }
    public HistorialContrasenias(PoliticaContrasenias politicaContrasenias, Usuario usuario, Date fechaCambio, String contraseniaNueva) {
       this.politicaContrasenias = politicaContrasenias;
       this.usuario = usuario;
       this.fechaCambio = fechaCambio;
       this.contraseniaNueva = contraseniaNueva;
    }
   
    public Integer getIdCambio() {
        return this.idCambio;
    }
    
    public void setIdCambio(Integer idCambio) {
        this.idCambio = idCambio;
    }
    public PoliticaContrasenias getPoliticaContrasenias() {
        return this.politicaContrasenias;
    }
    
    public void setPoliticaContrasenias(PoliticaContrasenias politicaContrasenias) {
        this.politicaContrasenias = politicaContrasenias;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaCambio() {
        return this.fechaCambio;
    }
    
    public void setFechaCambio(Date fechaCambio) {
        this.fechaCambio = fechaCambio;
    }
    public String getContraseniaNueva() {
        return this.contraseniaNueva;
    }
    
    public void setContraseniaNueva(String contraseniaNueva) {
        this.contraseniaNueva = contraseniaNueva;
    }




}


