package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1



/**
 * Informatica generated by hbm2java
 */
public class Informatica extends Aula  implements java.io.Serializable {


     private int idAula;
     private Aula aula;
     private String canion;
     private Integer cantidadPcs;

    public Informatica() {
    }

	
    public Informatica(Aula aula) {
        this.aula = aula;
    }
    public Informatica(Aula aula, String canion, Integer cantidadPcs) {
       this.aula = aula;
       this.canion = canion;
       this.cantidadPcs = cantidadPcs;
    }
   
    public int getIdAula() {
        return this.idAula;
    }
    
    public void setIdAula(int idAula) {
        this.idAula = idAula;
    }
    public Aula getAula() {
        return this.aula;
    }
    
    public void setAula(Aula aula) {
        this.aula = aula;
    }
    public String getCanion() {
        return this.canion;
    }
    
    public void setCanion(String canion) {
        this.canion = canion;
    }
    public Integer getCantidadPcs() {
        return this.cantidadPcs;
    }
    
    public void setCantidadPcs(Integer cantidadPcs) {
        this.cantidadPcs = cantidadPcs;
    }




}


