package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1



/**
 * Multimedios generated by hbm2java
 */
public class Multimedios extends Aula  implements java.io.Serializable {


     private int idAula;
     private String televisor;
     private String canion;
     private String computadora;
     private String dvd;

    public Multimedios() {
    }

    public Multimedios(String televisor, String canion, String computadora, String dvd) {
       this.televisor = televisor;
       this.canion = canion;
       this.computadora = computadora;
       this.dvd = dvd;
    }
    
    public void setIdAula(int idAula) {
        this.idAula = idAula;
    }
    public String getTelevisor() {
        return this.televisor;
    }
    
    public void setTelevisor(String televisor) {
        this.televisor = televisor;
    }
    public String getCanion() {
        return this.canion;
    }
    
    public void setCanion(String canion) {
        this.canion = canion;
    }
    public String getComputadora() {
        return this.computadora;
    }
    
    public void setComputadora(String computadora) {
        this.computadora = computadora;
    }
    public String getDvd() {
        return this.dvd;
    }
    
    public void setDvd(String dvd) {
        this.dvd = dvd;
    }




}


