package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;




/**
 * Periodica generated by hbm2java
 */
public class Periodica extends Reserva implements java.io.Serializable {

     private Periodo periodo;
     private Set dias = new HashSet(0);

    public Periodica() {
    }

    public Periodica(Periodo periodo) {
       this.periodo = periodo;
    }
   
    public Integer getIdReserva() {
        return super.getIdReserva();
    }
    
    public void setIdReserva(Integer idReserva) {
        super.setIdReserva(idReserva);
    }
    public Periodo getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Periodo periodo) {
        this.periodo = periodo;
    }

    public Set getDias() {
        return dias;
    }

    public void setDias(Set dias) {
        this.dias = dias;
    }
    
    

}


