package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Periodo generated by hbm2java
 */
public class Periodo  implements java.io.Serializable {


     private Integer idPeriodo;
     private String tipoPeriodo;
     private Date fechaInicio;
     private Date fechaFin;

    public Periodo() {
    }

    public Periodo(String tipoPeriodo, Date fechaInicio, Date fechaFin) {
       this.tipoPeriodo = tipoPeriodo;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public Integer getIdPeriodo() {
        return this.idPeriodo;
    }
    
    public void setIdPeriodo(Integer idPeriodo) {
        this.idPeriodo = idPeriodo;
    }
    public String getTipoPeriodo() {
        return this.tipoPeriodo;
    }
    
    public void setTipoPeriodo(String tipoPeriodo) {
        this.tipoPeriodo = tipoPeriodo;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


