package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1


/**
 * PoliticaContrasenias generated by hbm2java
 */
public class PoliticaContrasenias  implements java.io.Serializable {


     private Integer idPolitica;
     private String tipoPolitica;

    public PoliticaContrasenias() {
    }
   
    public Integer getIdPolitica() {
        return this.idPolitica;
    }
    
    public void setIdPolitica(Integer idPolitica) {
        this.idPolitica = idPolitica;
    }
    public String getTipoPolitica() {
        return this.tipoPolitica;
    }
    
    public void setTipoPolitica(String tipoPolitica) {
        this.tipoPolitica = tipoPolitica;
    }

}


