package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1



/**
 * SinRecursos generated by hbm2java
 */
public class SinRecursos extends Aula  implements java.io.Serializable {


     private int idAula;
     private String ventiladores;

    public SinRecursos() {
    }

    public SinRecursos(String ventiladores) {
       this.ventiladores = ventiladores;
    }
    
    public void setIdAula(int idAula) {
        this.idAula = idAula;
    }
    public String getVentiladores() {
        return this.ventiladores;
    }
    
    public void setVentiladores(String ventiladores) {
        this.ventiladores = ventiladores;
    }




}


