package db.model;
// Generated 24/10/2017 16:38:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombreUsuario;
     private String contrasenia;
     private Set historialContraseniases = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String nombreUsuario, String contrasenia) {
        this.nombreUsuario = nombreUsuario;
        this.contrasenia = contrasenia;
    }
    public Usuario(String nombreUsuario, String contrasenia, Set historialContraseniases) {
       this.nombreUsuario = nombreUsuario;
       this.contrasenia = contrasenia;
       this.historialContraseniases = historialContraseniases;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    
    public Set getHistorialContraseniases() {
        return this.historialContraseniases;
    }
    
    public void setHistorialContraseniases(Set historialContraseniases) {
        this.historialContraseniases = historialContraseniases;
    }
    
    public void addHistorial(HistorialContrasenias h) {
        this.historialContraseniases.add(h);
    }

}


